#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
<<<<<<< HEAD:mp4/xv6/b09901027/xv6/user/usys.pl
entry("symlink");
=======
# for mp3
entry("thrdstop");
entry("thrdresume");
entry("cancelthrdstop");

>>>>>>> 9029cc1fda289fb3b7e5ebb059a3e350e6fe90da:mp3/xv6-riscv/user/usys.pl
