status = "finished"
penalty = 0.0
total_score = 0.0

[mp2_1]
verdict = "error: expect va = 0x0000003fc0000000, but get 0x00000000000ff000 in line '+-- 255: pte=0x0000000087f497f8 va=0x00000000000ff000 pa=0x0000000087f48000 V'"
has_trailing_spaces = false
score = 0

[mp2_2]
verdict = "Program part I failed with error: unable to parse vmprint entry '': unable to parse entry ''"
has_trailing_spaces = false
score = 0

[mp2_3]
verdict = "madvise(MADV_NORMAL) test failed with error: unexpected output: panic: not implemented yet"
has_trailing_spaces = false
score = 0

[mp2_4]
verdict = "page fault test failed with error: unable to parse vmprint entry '': unable to parse entry ''"
has_trailing_spaces = false
score = 0

[violations]
has_invalid_zip_file_name = false
has_trailing_spaces = false
