status = "finished"
penalty = 0.0
total_score = 5.0

[mp2_1]
verdict = "pass"
has_trailing_spaces = false
score = 5

[mp2_2]
verdict = "Program part I failed with error: unable to parse vmprint entry '': unable to parse entry ''"
has_trailing_spaces = false
score = 0

[mp2_3]
verdict = "madvise(MADV_NORMAL) test failed with error: unexpected output: panic: not implemented yet"
has_trailing_spaces = false
score = 0

[mp2_4]
verdict = "page fault test failed with error: unable to parse vmprint entry '': unable to parse entry ''"
has_trailing_spaces = false
score = 0

[violations]
has_invalid_zip_file_name = false
has_trailing_spaces = false
